from setuptools import setup

setup(
    install_requires=[
        "absl-py==0.8.1",
        "cachetools==3.1.1",
        "certifi==2019.9.11",
        "chardet==3.0.4",
        "cycler==0.10.0",
        "google-auth==1.7.0",
        "google-auth-oauthlib==0.4.1",
        "grpcio==1.25.0",
        "idna==2.8",
        "kiwisolver==1.1.0",
        "markdown==3.1.1",
        "matplotlib==3.1.1",
        "numpy==1.17.4",
        "oauthlib==3.1.0",
        "pillow==6.2.1",
        "protobuf==3.10.0",
        "pyasn1==0.4.7",
        "pyasn1-modules==0.2.7",
        "pyparsing==2.4.5",
        "python-dateutil==2.8.1",
        "requests==2.22.0",
        "requests-oauthlib==1.3.0",
        "rsa==4.0",
        "six==1.13.0",
        "tensorboard==2.0.1",
        "torch==1.3.1",
        "torchvision==0.4.2",
        "urllib3==1.25.7",
        "werkzeug==0.16.0",
        "wheel==0.33.6; python_version >= '3'",
    ],
    name="myelin",
    description="A library for deep learning with spiking neural networks",
    url="http://github.com/cpehle/myelin",
    author="Christian Pehle",
    author_email="christian.pehle@gmail.com",
    packages=["myelin"],
)
