FROM nvidia/cuda:11.1-cudnn8-runtime-ubuntu20.04

RUN apt update && apt install -y python3-pip build-essential wget
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
RUN chmod +x miniconda.sh
RUN ./miniconda.sh -b -p /root/miniconda

RUN rm -rf /var/lib/apt/lists/ && rm miniconda.sh

RUN export PATH=$PATH:/root/miniconda/bin/
WORKDIR /norse

COPY . .

RUN pip3 install --upgrade pip
RUN pip3 install -e .
