FROM nvidia/cuda:12.9.0-cudnn-runtime-ubuntu24.04

RUN apt update && apt install -y git python3-pip build-essential
RUN rm -rf /var/lib/apt/lists/

WORKDIR /norse

COPY . .

RUN pip install torch torchvision torchaudio --break-system-packages
RUN pip install -e . --break-system-packages