{% set name = "norse" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../../

outputs:
  - name: norse
    files:
      - norse/
      - CMakeLists.txt
      - LICENSE
      - logo.png
      - norse_op.so
      - pyproject.toml
      - README.md
      - requirements.txt
      - setup.py
    test:
      requires:
        - pytest
        - pytest-xdist
      imports:
        - norse
        - torch
      source_files:
        - "**/*.py"
        - "*.so"
      commands:
        - pytest -n 4 -vv
    requirements:
      script:
        - python -m pip install --ignore-installed -e .
      build:
        - cmake
        - {{ compiler('cxx') }} # [win]
      host:
        - python
        - numpy=1.19
        - setuptools
        - pyyaml
        - mkl=2020.2 # [x86_64]
        - mkl-include # [x86_64]
        - typing_extensions
        - dataclasses # [py36]
        - ninja
        - libuv # [win]
        - libuv # [unix]
        - pkg-config # [unix]
      run:
        - python
        - pytorch>=1.9
        - torchvision>=0.10
        - ninja
        - typing_extensions
        - blas * mkl

about:
  home: https://github.com/norse/norse
  license: LGPLv3
  license_file: LICENSE
  summary: A library to do deep learning with spiking neural networks.
  description: |
    Norse expands PyTorch with primitives for bio-inspired neural components, bringing you two advantages: 
    a modern and proven infrastructure based on PyTorch and deep learning-compatible spiking neural network components.
  dev_url: https://github.com/norse/norse
  doc_url: https://norse.github.io/norse/
  doc_source_url: https://github.com/norse/norse/blob/master/README.md


extra:
  recipe-maintainers:
    - Jens E. Pedersen <jens@jepedersen.dk>
