name: Publish To Pypi

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pip install pep517
    - name: Build dist
      run: |
        python setup.py sdist
    - name: publish-to-pypi
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        AnacondaToken: ${{ secrets.PYPI_PUBLISH_KEY }}
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2010_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-38m cp39-39m'
        system-packages: gcc-c++ glibc
    - name: Publish wheels to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PUBLISH_KEY }}
      run: |
        twine upload dist/*-manylinux*.whl