name: Publish full version docker images

on:
  release:
    types: [published]

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: "norse+github_actions"
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push vanilla
        id: docker_build_vanilla
        uses: docker/build-push-action@v2
        with:
          context: .
          file: publish/Dockerfile
          push: true
          tags: quay.io/norse/norse:${{ GITHUB_REF }},quay.io/norse/norse:latest

      - name: Image digest
        run: echo ${{ steps.docker_build_vanilla.outputs.digest }}

      - name: Build and push miniconda
        id: docker_build_conda
        uses: docker/build-push-action@v2
        with:
          context: .
          file: publish/Dockerfile.conda
          push: true
          tags: quay.io/norse/norse:${{ GITHUB_REF }}-conda,quay.io/norse/norse:latest-conda

      - name: Image digest
        run: echo ${{ steps.docker_build_conda.outputs.digest }}
