name: Build via Spack (nightly)

on:
  schedule:
    - cron: '4 2 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@master
      - name: Spack cache
        uses: actions/cache@v2
        with:
          path: ~/.spack-cache
          key: cache-spack-main-latest
      - name: Build norse's Spack package
        run: .github/spack/build_spack_package.sh
